language: node_js

node_js:
- '6.6'

install:
- npm install

script:
- npm test

notifications:
  slack: teamtaverna:iP55LweubU8UOBgu9e0cTeED

deploy:
  provider: heroku
  api_key:
    secure: o+Lhw3PDuV3DpuwQ64Ve9qfgMSME9dpcLlHXU3eO41n+5ZdnnovcOvaD1hKxrLAH1SGdbSgsqKHxkZsSBlNX7SSSEO2oQtfAPneUjyfsJ37Z8MvYY355Srm9kZ2yaUwQqyTvvZORz4fDqm1DNrnSZDdPSWKpfDGqzm12HHRmz8+aql9C8DQotro1PsD3pXKUD2sIBksUuJ+AMqj01xu+BHj+ppbSe+wqGxa9M3uAPL0JEw8MbVKO9np8SKz1HwDXt98Qn1jqbEQpISpjCB+nq9ILKjK0KNVDsEYzZePYsI5lxkgdknsX2DYW5yu1QvQnF6g+LmxQ4hS7tDE2WiEAftnGL+s2lKXo5W0Mity2Q9sDnZtxaeeEWSLeaJclpsMUjAJARcK2TIturK+lCS7XKautccvovzr0CaJlJanwbl+6eu02wvlqqY1XtoUA+M5ijrakQvdWMV7F3FK/PPaigQw+EpQShk1QA1MneAGY3GOX6xtiezzRBaQgDP1ZxP478vXGk8VMVuyfTPLUiKrjxcyPxlprJEbVeYsWfrYUSTit7P1Y+DbLC7e/pxKktPCHh1fdtyOAI20ss/BlxrR/ixzW7SPf9kJ5nv+IDicThveyBS1J63l3T4VVPIDN14gqArzS9lktJHyr1qCcgI6tSJgIGE8k6DEHKMNhk6bAy3M=
  app:
    master: taverna-webclient
    staging: taverna-webclient-staging
